set dotenv-load

create day:
    cargo generate --path ./day-template --name day-{{day}} -d day={{day}}

run day:
    cargo run --bin day{{day}}

get-input day:
    ./scripts/get-aoc-input.rs --day {{day}} --current-working-directory {{justfile_directory()}}
